/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarvelRouteImport } from './routes/marvel'
import { Route as DcRouteImport } from './routes/dc'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HeroIdRouteImport } from './routes/hero.$id'

const MarvelRoute = MarvelRouteImport.update({
  id: '/marvel',
  path: '/marvel',
  getParentRoute: () => rootRouteImport,
} as any)
const DcRoute = DcRouteImport.update({
  id: '/dc',
  path: '/dc',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroIdRoute = HeroIdRouteImport.update({
  id: '/hero/$id',
  path: '/hero/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dc': typeof DcRoute
  '/marvel': typeof MarvelRoute
  '/hero/$id': typeof HeroIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dc': typeof DcRoute
  '/marvel': typeof MarvelRoute
  '/hero/$id': typeof HeroIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dc': typeof DcRoute
  '/marvel': typeof MarvelRoute
  '/hero/$id': typeof HeroIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dc' | '/marvel' | '/hero/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dc' | '/marvel' | '/hero/$id'
  id: '__root__' | '/' | '/dc' | '/marvel' | '/hero/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DcRoute: typeof DcRoute
  MarvelRoute: typeof MarvelRoute
  HeroIdRoute: typeof HeroIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/marvel': {
      id: '/marvel'
      path: '/marvel'
      fullPath: '/marvel'
      preLoaderRoute: typeof MarvelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dc': {
      id: '/dc'
      path: '/dc'
      fullPath: '/dc'
      preLoaderRoute: typeof DcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hero/$id': {
      id: '/hero/$id'
      path: '/hero/$id'
      fullPath: '/hero/$id'
      preLoaderRoute: typeof HeroIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DcRoute: DcRoute,
  MarvelRoute: MarvelRoute,
  HeroIdRoute: HeroIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
