// Imágenes reales obtenidas desde la API pública Superhero API
// (https://github.com/akabab/superhero-api), servida vía jsDelivr CDN.
const REAL_IMAGES = {
  "spider-man": ["https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/620-spider-man.jpg"],
  "iron-man": ["https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/346-iron-man.jpg"],
  "captain-america": ["https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/149-captain-america.jpg"],
  "thor": ["https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/659-thor.jpg"],
  "hulk": ["https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/332-hulk.jpg"],
  "black-widow": ["https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/107-black-widow.jpg"],
  "hawkeye": ["https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/313-hawkeye.jpg"],
  "doctor-strange": ["https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/226-doctor-strange.jpg"],
  "black-panther": ["https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/106-black-panther.jpg"],
  "wolverine": ["https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/717-wolverine.jpg"],
  "deadpool": ["https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/213-deadpool.jpg"],
  "storm": ["https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/638-storm.jpg"],
  "scarlet-witch": ["https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/579-scarlet-witch.jpg"],
  "vision": ["https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/697-vision.jpg"],
  "ant-man": [
    "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/30-ant-man.jpg",
    "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/31-ant-man-ii.jpg",
  ],
  "captain-marvel": [
    "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/158-captain-marvel-ii.jpg",
    "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/156-captain-marvel.jpg",
  ],
  "daredevil": ["https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/201-daredevil.jpg"],
  "silver-surfer": ["https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/598-silver-surfer.jpg"],
  "thanos": ["https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/655-thanos.jpg"],
  "venom": ["https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/687-venom.jpg"],
  "superman": ["https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/644-superman.jpg"],
  "batman": [
    "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/70-batman.jpg",
    "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/69-batman.jpg",
  ],
  "wonder-woman": ["https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/720-wonder-woman.jpg"],
  "flash": [
    "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/265-flash-ii.jpg",
    "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/263-flash.jpg",
  ],
  "green-lantern": ["https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/306-hal-jordan.jpg"],
  "aquaman": ["https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/38-aquaman.jpg"],
  "cyborg": ["https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/194-cyborg.jpg"],
  "green-arrow": ["https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/298-green-arrow.jpg"],
  "shazam": ["https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/156-captain-marvel.jpg"],
  "martian-manhunter": ["https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/432-martian-manhunter.jpg"],
  "nightwing": ["https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/491-nightwing.jpg"],
  "robin": [
    "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/561-robin.jpg",
    "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/564-robin-v.jpg",
  ],
  "supergirl": ["https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/643-supergirl.jpg"],
  "batgirl": [
    "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/63-batgirl.jpg",
    "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/66-batgirl-iv.jpg",
  ],
  "catwoman": ["https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/165-catwoman.jpg"],
  "harley-quinn": ["https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/309-harley-quinn.jpg"],
  "joker": ["https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/370-joker.jpg"],
  "lex-luthor": ["https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/405-lex-luthor.jpg"],
  "darkseid": ["https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/204-darkseid.jpg"],
  "zatanna": ["https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/730-zatanna.jpg"],
};

const stylized = (name, house) => {
  const bg = house === "marvel" ? "ED1D24" : "0476F2";
  return `https://placehold.co/600x800/${bg}/FFFFFF/png?text=${encodeURIComponent(name)}&font=montserrat`;
};

const buildImages = (id, name, house) => {
  const real = REAL_IMAGES[id] || [];
  if (real.length >= 2) return real;
  if (real.length === 1) return [real[0], stylized(name, house)];
  return [stylized(name, house)];
};

const seeds = [
  // ===== MARVEL (20) =====
  { id: "spider-man", name: "Spider-Man", realName: "Peter Parker", appearanceYear: 1962, house: "marvel",
    biography: "Mordido por una araña radiactiva, Peter Parker obtuvo poderes arácnidos y aprendió que un gran poder conlleva una gran responsabilidad. Defiende Nueva York como el trepamuros amistoso.",
    equipment: ["Lanzatelarañas", "Traje arácnido", "Sentido arácnido"] },
  { id: "iron-man", name: "Iron Man", realName: "Tony Stark", appearanceYear: 1963, house: "marvel",
    biography: "Genio millonario y filántropo, Tony Stark construyó una armadura tecnológica tras ser secuestrado, transformándose en un héroe blindado y miembro fundador de los Vengadores.",
    equipment: ["Armadura Mark LXXXV", "Repulsores", "J.A.R.V.I.S."] },
  { id: "captain-america", name: "Captain America", realName: "Steve Rogers", appearanceYear: 1941, house: "marvel",
    biography: "Un joven enfermizo transformado en súper soldado durante la Segunda Guerra Mundial. Símbolo de libertad y justicia, lidera a los Vengadores con su escudo de vibranium.",
    equipment: ["Escudo de vibranium", "Suero del súper soldado"] },
  { id: "thor", name: "Thor", realName: "Thor Odinson", appearanceYear: 1962, house: "marvel",
    biography: "Príncipe asgardiano y dios del trueno, blande el martillo Mjolnir. Defiende los Nueve Reinos junto a los Vengadores.",
    equipment: ["Mjolnir", "Stormbreaker", "Cinturón de fuerza"] },
  { id: "hulk", name: "Hulk", realName: "Bruce Banner", appearanceYear: 1962, house: "marvel",
    biography: "Tras una explosión de rayos gamma, el científico Bruce Banner se transforma en el monstruo verde más fuerte del planeta cuando se enoja." },
  { id: "black-widow", name: "Black Widow", realName: "Natasha Romanoff", appearanceYear: 1964, house: "marvel",
    biography: "Ex-espía soviética entrenada en la Habitación Roja, ahora héroe y miembro clave de los Vengadores. Maestra del espionaje y combate cuerpo a cuerpo.",
    equipment: ["Picaduras de viuda", "Pistolas Glock", "Bastones eléctricos"] },
  { id: "hawkeye", name: "Hawkeye", realName: "Clint Barton", appearanceYear: 1964, house: "marvel",
    biography: "Arquero de élite y agente de S.H.I.E.L.D., su puntería sobrehumana lo convierte en uno de los Vengadores más letales sin superpoderes.",
    equipment: ["Arco compuesto", "Flechas trick"] },
  { id: "doctor-strange", name: "Doctor Strange", realName: "Stephen Strange", appearanceYear: 1963, house: "marvel",
    biography: "Antiguo neurocirujano convertido en Hechicero Supremo. Protege la realidad de amenazas místicas y dimensionales.",
    equipment: ["Capa de Levitación", "Ojo de Agamotto", "Libro de Vishanti"] },
  { id: "black-panther", name: "Black Panther", realName: "T'Challa", appearanceYear: 1966, house: "marvel",
    biography: "Rey de Wakanda y protector ancestral de su pueblo. Combina ciencia avanzada de vibranium con tradición y honor.",
    equipment: ["Traje de vibranium", "Garras energéticas", "Hierba en forma de corazón"] },
  { id: "wolverine", name: "Wolverine", realName: "James Howlett", appearanceYear: 1974, house: "marvel",
    biography: "Mutante con factor curativo y esqueleto recubierto de adamantium. X-Man legendario con un pasado violento y memorias fragmentadas.",
    equipment: ["Garras de adamantium", "Factor curativo"] },
  { id: "deadpool", name: "Deadpool", realName: "Wade Wilson", appearanceYear: 1991, house: "marvel",
    biography: "Mercenario bocazas con factor curativo extremo. Rompe la cuarta pared y combina humor absurdo con violencia extrema.",
    equipment: ["Katanas", "Pistolas", "Factor curativo"] },
  { id: "storm", name: "Storm", realName: "Ororo Munroe", appearanceYear: 1975, house: "marvel",
    biography: "Mutante capaz de controlar el clima. Líder de los X-Men y reina de Wakanda en algún momento de su historia." },
  { id: "scarlet-witch", name: "Scarlet Witch", realName: "Wanda Maximoff", appearanceYear: 1964, house: "marvel",
    biography: "Hechicera con magia del caos capaz de alterar la realidad. Su poder la convierte en una de las heroínas más poderosas de Marvel." },
  { id: "vision", name: "Vision", appearanceYear: 1968, house: "marvel",
    biography: "Sintezoide creado por Ultron, alimentado por la Gema de la Mente. Vengador con cuerpo de vibranium y alma sintética.",
    equipment: ["Gema de la Mente", "Densidad variable"] },
  { id: "ant-man", name: "Ant-Man", realName: "Scott Lang", appearanceYear: 1979, house: "marvel",
    biography: "Ex-ladrón que hereda el traje de Ant-Man de Hank Pym. Puede cambiar de tamaño y comunicarse con hormigas.",
    equipment: ["Traje Pym", "Partículas Pym", "Casco regulador"] },
  { id: "captain-marvel", name: "Captain Marvel", realName: "Carol Danvers", appearanceYear: 1968, house: "marvel",
    biography: "Piloto de la Fuerza Aérea fusionada con ADN Kree. Una de las heroínas más poderosas del universo Marvel." },
  { id: "daredevil", name: "Daredevil", realName: "Matt Murdock", appearanceYear: 1964, house: "marvel",
    biography: "Abogado ciego con sentidos sobrehumanos que protege Hell's Kitchen como un vigilante sin miedo.",
    equipment: ["Bastón billy club", "Traje rojo"] },
  { id: "silver-surfer", name: "Silver Surfer", realName: "Norrin Radd", appearanceYear: 1966, house: "marvel",
    biography: "Heraldo cósmico de Galactus que viaja por el universo en su tabla plateada, dotado del Poder Cósmico.",
    equipment: ["Tabla cósmica", "Poder Cósmico"] },
  { id: "thanos", name: "Thanos", appearanceYear: 1973, house: "marvel",
    biography: "El Titán Loco, obsesionado con la muerte y el equilibrio del universo. Antagonista cósmico portador del Guantelete del Infinito.",
    equipment: ["Guantelete del Infinito", "Gemas del Infinito"] },
  { id: "venom", name: "Venom", realName: "Eddie Brock", appearanceYear: 1988, house: "marvel",
    biography: "Periodista vinculado a un simbionte alienígena. Antihéroe brutal con habilidades arácnidas amplificadas.",
    equipment: ["Simbionte Klyntar"] },

  // ===== DC (20) =====
  { id: "superman", name: "Superman", realName: "Clark Kent / Kal-El", appearanceYear: 1938, house: "dc",
    biography: "Último hijo de Krypton criado en Smallville. Bajo el sol amarillo gana poderes increíbles y se convierte en el símbolo de esperanza de la humanidad.",
    equipment: ["Capa indestructible", "Traje kryptoniano"] },
  { id: "batman", name: "Batman", realName: "Bruce Wayne", appearanceYear: 1939, house: "dc",
    biography: "Tras presenciar el asesinato de sus padres, Bruce Wayne dedica su vida y fortuna a combatir el crimen en Gotham como el Caballero de la Noche.",
    equipment: ["Batitraje", "Batarangs", "Cinturón multiusos", "Batimóvil"] },
  { id: "wonder-woman", name: "Wonder Woman", realName: "Diana Prince", appearanceYear: 1941, house: "dc",
    biography: "Princesa amazona de Themyscira, embajadora de la paz y guerrera invencible. Hija de Zeus y campeona de la verdad.",
    equipment: ["Lazo de la Verdad", "Brazaletes de sumisión", "Tiara"] },
  { id: "flash", name: "The Flash", realName: "Barry Allen", appearanceYear: 1956, house: "dc",
    biography: "Científico forense alcanzado por un rayo y bañado en químicos. Conectado a la Fuerza de la Velocidad, es el hombre más rápido del mundo.",
    equipment: ["Traje aerodinámico", "Anillo compresor"] },
  { id: "green-lantern", name: "Green Lantern", realName: "Hal Jordan", appearanceYear: 1959, house: "dc",
    biography: "Piloto de pruebas elegido por un anillo de poder. Miembro del Cuerpo de Linternas Verdes, defensor del sector 2814.",
    equipment: ["Anillo de poder", "Batería verde"] },
  { id: "aquaman", name: "Aquaman", realName: "Arthur Curry", appearanceYear: 1941, house: "dc",
    biography: "Rey de Atlántida e híbrido humano-atlante. Capaz de comunicarse con la vida marina y comandar los océanos.",
    equipment: ["Tridente de Neptuno"] },
  { id: "cyborg", name: "Cyborg", realName: "Victor Stone", appearanceYear: 1980, house: "dc",
    biography: "Atleta universitario reconstruido con tecnología alienígena tras un terrible accidente. Mitad humano, mitad máquina, miembro de la Liga de la Justicia.",
    equipment: ["Cañón de sonido", "Boom Tube integrado"] },
  { id: "green-arrow", name: "Green Arrow", realName: "Oliver Queen", appearanceYear: 1941, house: "dc",
    biography: "Millonario convertido en justiciero arquero tras estar varado en una isla. Defiende Star City con flechas trick.",
    equipment: ["Arco compuesto", "Flechas especiales"] },
  { id: "shazam", name: "Shazam", realName: "Billy Batson", appearanceYear: 1940, house: "dc",
    biography: "Niño huérfano que al pronunciar 'Shazam' se transforma en un héroe adulto con los poderes de seis dioses antiguos." },
  { id: "martian-manhunter", name: "Martian Manhunter", realName: "J'onn J'onzz", appearanceYear: 1955, house: "dc",
    biography: "Último marciano verde, telépata, telequinético y cambiaformas. Miembro fundador de la Liga de la Justicia." },
  { id: "nightwing", name: "Nightwing", realName: "Dick Grayson", appearanceYear: 1984, house: "dc",
    biography: "El primer Robin, ahora héroe independiente que protege Blüdhaven. Acróbata sin igual y líder nato.",
    equipment: ["Escrimas eléctricas", "Traje azul"] },
  { id: "robin", name: "Robin", realName: "Damian Wayne", appearanceYear: 1940, house: "dc",
    biography: "El compañero juvenil de Batman. Damian Wayne, hijo biológico de Bruce, criado entre asesinos y entrenado para la justicia.",
    equipment: ["Katana", "Capa", "Gadgets de Bat"] },
  { id: "supergirl", name: "Supergirl", realName: "Kara Zor-El", appearanceYear: 1959, house: "dc",
    biography: "Prima de Superman, también superviviente de Krypton. Heroína con los mismos poderes solares que su famoso primo." },
  { id: "batgirl", name: "Batgirl", realName: "Barbara Gordon", appearanceYear: 1967, house: "dc",
    biography: "Hija del comisionado Gordon, brillante hacker y vigilante. Aliada clave de la Bati-familia.",
    equipment: ["Traje de Batgirl", "Batarangs", "Computadora"] },
  { id: "catwoman", name: "Catwoman", realName: "Selina Kyle", appearanceYear: 1940, house: "dc",
    biography: "Ladrona felina de Gotham, antiheroína y eterno interés amoroso de Batman. Maestra del sigilo y la astucia.",
    equipment: ["Látigo", "Garras", "Traje de cuero"] },
  { id: "harley-quinn", name: "Harley Quinn", realName: "Harleen Quinzel", appearanceYear: 1992, house: "dc",
    biography: "Ex-psiquiatra de Arkham seducida por el Joker. Antiheroína caótica con un mazo enorme y humor demencial.",
    equipment: ["Mazo gigante", "Bate de béisbol"] },
  { id: "joker", name: "Joker", appearanceYear: 1940, house: "dc",
    biography: "El payaso príncipe del crimen. El archienemigo de Batman, un agente del caos sin nombre real conocido.",
    equipment: ["Gas de la risa", "Cartas afiladas", "Joybuzzer"] },
  { id: "lex-luthor", name: "Lex Luthor", realName: "Alexander Luthor", appearanceYear: 1940, house: "dc",
    biography: "Genio multimillonario y archienemigo de Superman. CEO de LexCorp y obsesionado con derrocar al Hombre de Acero.",
    equipment: ["Armadura de combate", "Tecnología kryptoniana"] },
  { id: "darkseid", name: "Darkseid", realName: "Uxas", appearanceYear: 1970, house: "dc",
    biography: "Tirano de Apokolips, dios del mal y portador de la Ecuación Anti-Vida. Una de las amenazas cósmicas más temidas.",
    equipment: ["Rayos Omega", "Ecuación Anti-Vida"] },
  { id: "zatanna", name: "Zatanna", realName: "Zatanna Zatara", appearanceYear: 1964, house: "dc",
    biography: "Maga homo magi que conjura hechizos pronunciando palabras al revés. Miembro de la Liga de la Justicia Oscura.",
    equipment: ["Sombrero de copa", "Varita mágica"] },
];

export const seedHeroes = seeds.map((s) => ({
  ...s,
  images: buildImages(s.id, s.name, s.house),
}));
